### ISSUE TITLE
kyori MiniMessage error, cannot use /send

### ISSUE THREAD

**Issue by therbz** [OskarsMC-Plugins/send#8]
When attempting to /send any player, server, group, or all, the following error is printed:
```
[09:52:11 INFO]: Exception occurred while running command for therbz
java.util.concurrent.CompletionException: java.lang.RuntimeException: Unable to invoke command send player therbz1 SMP for [connected player] therbz (/31.54.80.3:60781)
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.RuntimeException: Unable to invoke command send player therbz1 SMP for [connected player] therbz (/31.54.80.3:60781)
        at com.velocitypowered.proxy.command.VelocityCommandManager.executeImmediately0(VelocityCommandManager.java:223) ~[velocity.jar:3.1.2-SNAPSHOT (git-05d19384-b125)]
        at com.velocitypowered.proxy.command.VelocityCommandManager.lambda$executeImmediatelyAsync$1(VelocityCommandManager.java:248) ~[velocity.jar:3.1.2-SNAPSHOT (git-05d19384-b125)]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        ... 3 more
Caused by: java.lang.NoSuchMethodError: 'net.kyori.adventure.text.minimessage.MiniMessage net.kyori.adventure.text.minimessage.MiniMessage.get()'
        at com.oskarsmc.send.command.SendCommand.sendMessage(SendCommand.java:148) ~[?:?]
        at com.oskarsmc.send.command.SendCommand.lambda$new$0(SendCommand.java:51) ~[?:?]
        at cloud.commandframework.execution.CommandExecutionCoordinator$SimpleCoordinator.coordinateExecution(CommandExecutionCoordinator.java:121) ~[?:?]
        at cloud.commandframework.CommandManager.executeCommand(CommandManager.java:176) ~[?:?]
        at cloud.commandframework.velocity.VelocityExecutor.run(VelocityExecutor.java:64) ~[?:?]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:262) ~[velocity.jar:3.1.2-SNAPSHOT (git-05d19384-b125)]
        at com.velocitypowered.proxy.command.VelocityCommandManager.executeImmediately0(VelocityCommandManager.java:210) ~[velocity.jar:3.1.2-SNAPSHOT (git-05d19384-b125)]
        at com.velocitypowered.proxy.command.VelocityCommandManager.lambda$executeImmediatelyAsync$1(VelocityCommandManager.java:248) ~[velocity.jar:3.1.2-SNAPSHOT (git-05d19384-b125)]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        ... 3 more
```
I'm using velocity build #125, send 2.0.0, java 17.

**Comment by therbz** [comment]
Compiled the plugin myself and it now works, only change I made was changing the scope of minimessage from provided to compile but I haven't tested to see if that caused it to work again.
