### ISSUE TITLE
[BUG] Command Error

### ISSUE THREAD

**Issue by lightumcc** [OskarsMC-Plugins/send#9]
Cannot send user to server
Velocity 3.1.2-SNAPSHOT (git-62bd58d3-b167)
Server version: 1.19
JDK 17
Linux Debian 4.19.208-1 (2021-09-29) 4.19.0-18-amd64

Exception occurred while running command for lightum_cc
java.util.concurrent.CompletionException: java.lang.RuntimeException: Unable to invoke command send all lobby for [connected player] lightum_cc (/XXXXXX:XXXX)
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.RuntimeException: Unable to invoke command send all lobby for [connected player] lightum_cc (/58.39.110.106:52936)
        at com.velocitypowered.proxy.command.VelocityCommandManager.executeImmediately0(VelocityCommandManager.java:223) ~[velocity-3.1.2-SNAPSHOT-167.jar:3.1.2-SNAPSHOT (git-62bd58d3-b167)]
        at com.velocitypowered.proxy.command.VelocityCommandManager.lambda$executeImmediatelyAsync$1(VelocityCommandManager.java:248) ~[velocity-3.1.2-SNAPSHOT-167.jar:3.1.2-SNAPSHOT (git-62bd58d3-b167)]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        ... 3 more
Caused by: java.lang.NoSuchMethodError: 'net.kyori.adventure.text.minimessage.MiniMessage net.kyori.adventure.text.minimessage.MiniMessage.get()'
        at com.oskarsmc.send.command.SendCommand.sendMessage(SendCommand.java:150) ~[?:?]
        at com.oskarsmc.send.command.SendCommand.lambda$new$2(SendCommand.java:77) ~[?:?]
        at cloud.commandframework.execution.CommandExecutionCoordinator$SimpleCoordinator.coordinateExecution(CommandExecutionCoordinator.java:121) ~[?:?]
        at cloud.commandframework.CommandManager.executeCommand(CommandManager.java:176) ~[?:?]
        at cloud.commandframework.velocity.VelocityExecutor.run(VelocityExecutor.java:64) ~[?:?]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:262) ~[velocity-3.1.2-SNAPSHOT-167.jar:3.1.2-SNAPSHOT (git-62bd58d3-b167)]
        at com.velocitypowered.proxy.command.VelocityCommandManager.executeImmediately0(VelocityCommandManager.java:210) ~[velocity-3.1.2-SNAPSHOT-167.jar:3.1.2-SNAPSHOT (git-62bd58d3-b167)]
        at com.velocitypowered.proxy.command.VelocityCommandManager.lambda$executeImmediatelyAsync$1(VelocityCommandManager.java:248) ~[velocity-3.1.2-SNAPSHOT-167.jar:3.1.2-SNAPSHOT (git-62bd58d3-b167)]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        ... 3 more

**Comment by OskarZyg** [comment]
should be resolved in 3.0.0
